name: Build Docker Image and Save as File

on:
  workflow_dispatch:  # 仅允许手动触发工作流

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          docker build -t my-image .

      - name: Save Docker image to file
        run: |
          docker save my-image | gzip > my-image.tar.gz
          
      - name: Upload Docker image as artifact
        uses: actions/upload-artifact@v3  # 升级到 v3
        with:
          name: my-image
          path: my-image.tar.gz
